

ACCOUNT_LEDGER_FIELDS = [
    "id",
    "ledger_group_id",
    "transaction_uid",
    "transaction_type",
    "transaction_id",
    "source_kind",
    "source_id",
    "date",
    "effective_date",
    "account_id",
    "account_name_snapshot",
    "counterparty_account_id",
    "counterparty_account_name_snapshot",
    "payment_method_id",
    "payment_method_name_snapshot",
    "movement_kind",
    "direction",
    "amount",
    "currency",
    "signed_amount",
    "status",
    "is_void",
    "voided_by_ledger_group_id",
    "created_from_resolution_json",
    "notes",
    "created_at",
]

TRANSACTION_FIELDS = [
    "id",
    "transaction_uid",
    "date",
    "category",
    "sub_category",
    "amount",
    "original_amount",
    "original_currency",
    "exchange_rate_to_eur",
    "exchange_correction_to_eur",
    "exchange_effective_rate_to_eur",
    "account",
    "account_id",
    "account_key_snapshot",
    "account_name_snapshot",
    "account_due_day_snapshot",
    # Optional payment/contact/ledger metadata. Older CSVs are migrated
    # automatically with blank values by repositories.csv_files.ensure_csv().
    "payment_method",
    "payment_method_id",
    "payment_method_name_snapshot",
    "payment_channel_method_id_snapshot",
    "payment_channel_name_snapshot",
    "funding_account_id_snapshot",
    "funding_account_name_snapshot",
    "settlement_account_id_snapshot",
    "settlement_account_name_snapshot",
    "liability_account_id_snapshot",
    "liability_account_name_snapshot",
    "settlement_mode_snapshot",
    "payment_due_date_snapshot",
    "payment_due_day_snapshot",
    "payment_statement_period_snapshot",
    "payment_resolution_json",
    "ledger_group_id",
    "ledger_status",
    "contact_id",
    "contact_name",
    "iban_snapshot",
    "bic_swift_snapshot",
    "bank_name_snapshot",
    "transfer_reference",
    "transfer_status",
    "description",
    "created_at",
]


INTERNAL_TRANSFER_FIELDS = [
    "id",
    "transfer_uid",
    "date",
    # Legacy display fields retained for old CSV compatibility.
    "from_account",
    "to_account",
    # Stable account-routing fields used by the ledger-backed flow.
    "from_account_id",
    "from_account_name_snapshot",
    "to_account_id",
    "to_account_name_snapshot",
    "amount",
    "fee_amount",
    "fee_payment_method_id",
    "fee_payment_method_name_snapshot",
    "ledger_group_id",
    "status",
    "transfer_kind",
    "metadata_json",
    "description",
    "created_at",
    "updated_at",
]

CREDIT_SETTLEMENT_FIELDS = [
    "id",
    "settlement_uid",
    "payment_method_id",
    "payment_method_name_snapshot",
    "liability_account_id",
    "liability_account_name_snapshot",
    "settlement_account_id",
    "settlement_account_name_snapshot",
    "statement_period",
    "due_date",
    "amount",
    "currency",
    "status",
    "ledger_group_id",
    "pending_id",
    "executed_transaction_uid",
    "created_from_ledger_group_ids_json",
    "created_at",
    "updated_at",
    "executed_at",
    "notes",
]

PENDING_FIELDS = [
    "id",
    "type",
    "date_due",
    "amount",
    "category",
    "account",
    "description",
    "status",
    "source",
    "source_id",
    # Optional metadata used by credit-account statement aggregation.
    # Older CSVs are migrated automatically and keep working with blanks.
    "pending_kind",
    "account_key",
    "account_label",
    "statement_month",
    "date_charge",
    "account_id",
    "account_name_snapshot",
    "payment_method_id",
    "payment_method_name_snapshot",
    "payment_resolution_template_json",
]

RECURRING_FIELDS = [
    "id",
    "name",
    "type",
    "amount",
    "frequency",
    "day_of_month",
    "category",
    "account",
    "start_date",
    "end_date",
    "max_occurrences",
    "last_generated",
    "account_id",
    "account_name_snapshot",
    "payment_method_id",
    "payment_method_name_snapshot",
    "payment_resolution_template_json",
]

SPARAGNAT_FIELDS = [
    "id",
    "transaction_uid",
    "date",
    "kind",
    "person",
    "category",
    "amount",
    "original_amount",
    "original_currency",
    "exchange_rate_to_eur",
    "exchange_correction_to_eur",
    "exchange_effective_rate_to_eur",
    "account",
    "account_id",
    "account_key_snapshot",
    "account_name_snapshot",
    "account_due_day_snapshot",
    # Optional payment/contact/ledger metadata. Older CSVs are migrated
    # automatically with blank values by repositories.csv_files.ensure_csv().
    "payment_method",
    "payment_method_id",
    "payment_method_name_snapshot",
    "payment_channel_method_id_snapshot",
    "payment_channel_name_snapshot",
    "funding_account_id_snapshot",
    "funding_account_name_snapshot",
    "settlement_account_id_snapshot",
    "settlement_account_name_snapshot",
    "liability_account_id_snapshot",
    "liability_account_name_snapshot",
    "settlement_mode_snapshot",
    "payment_due_date_snapshot",
    "payment_due_day_snapshot",
    "payment_statement_period_snapshot",
    "payment_resolution_json",
    "ledger_group_id",
    "ledger_status",
    "contact_id",
    "contact_name",
    "iban_snapshot",
    "bic_swift_snapshot",
    "bank_name_snapshot",
    "transfer_reference",
    "transfer_status",
    "description",
    "created_at",
]

PARENT_SUPPORT_FIELDS = [
    "id",
    "date",
    "kind",
    "parent",
    "category",
    "amount",
    "payment_method",
    "description",
    "created_at",
    "account_id",
    "account_name_snapshot",
    "payment_method_id",
    "payment_method_name_snapshot",
]

PARENT_SUPPORT_RULE_FIELDS = [
    "id",
    "name",
    "kind",
    "parent",
    "category",
    "monthly_amount",
    "day_of_month",
    "start_date",
    "end_date",
    "payment_method",
    "description",
    "active",
    "created_at",
    "account_id",
    "account_name_snapshot",
    "payment_method_id",
    "payment_method_name_snapshot",
]

DEBT_FIELDS = [
    "id",
    "name",
    "creditor",
    "original_amount",
    "remaining_amount",
    "category",
    "account",
    "start_date",
    "due_date",
    "description",
    "status",
    "created_at",
    "closed_at",
    "account_id",
    "account_name_snapshot",
    "preferred_payment_method_id",
    "preferred_payment_method_name_snapshot",
]

DEBT_RULE_FIELDS = [
    "id",
    "debt_id",
    "name",
    "rule_type",
    "amount",
    "frequency",
    "day_of_month",
    "start_date",
    "payoff_date",
    "last_generated",
    "active",
]

RECEIVABLE_FIELDS = [
    "id",
    "name",
    "debtor",
    "original_amount",
    "remaining_amount",
    "account",
    "start_date",
    "due_date",
    "description",
    "status",
    "linked_expense_transaction_id",
    "created_at",
    "closed_at",
    "account_id",
    "account_name_snapshot",
    "preferred_payment_method_id",
    "preferred_payment_method_name_snapshot",
]

PAYABLE_FIELDS = [
    "id",
    "name",
    "payee",
    "original_amount",
    "remaining_amount",
    "category",
    "account",
    "start_date",
    "due_date",
    "description",
    "status",
    "created_at",
    "closed_at",
    "account_id",
    "account_name_snapshot",
    "preferred_payment_method_id",
    "preferred_payment_method_name_snapshot",
]

EXPENSE_PROJECT_FIELDS = [
    "id",
    "name",
    "category",
    "description",
    "status",
    "created_at",
    "closed_at",
]

EXPENSE_PROJECT_MOVEMENT_FIELDS = [
    "id",
    "project_id",
    "transaction_type",
    "transaction_id",
    "source",
    "note",
    "created_at",
]

EXPENSE_PROJECT_PLANNED_ITEM_FIELDS = [
    "id",
    "project_id",
    "name",
    "vendor",
    "original_amount",
    "remaining_amount",
    "category",
    "sub_category",
    "account",
    "start_date",
    "due_date",
    "description",
    "status",
    # Optional foreign key to the current user payables CSV. When present, the row is only
    # a project forecast link: Payables remains the source of truth.
    "payable_id",
    "created_at",
    "closed_at",
    "account_id",
    "account_name_snapshot",
    "preferred_payment_method_id",
    "preferred_payment_method_name_snapshot",
]

INVESTMENT_ASSET_FIELDS = [
    "id",
    "symbol",
    "label",
    "allocation_pct",
    "currency",
    "active",
    "created_at",
    "funding_account_id",
    "funding_account_name_snapshot",
    "payment_method_id",
    "payment_method_name_snapshot",
]

WEEKDAY_ORDER = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
]
